name: highvibe
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.0.1+1

environment:
  sdk: ">=2.8.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  agora_rtc_engine: 1.0.5
  audioplayers: ^0.15.1
  camera: ^0.5.7+4
  dio: ^3.0.9
  easy_permission_validator: ^2.0.0
  flutter_apns: ^1.1.0
  flutter_local_notifications: ^1.4.1
  flutter_svg: ^0.17.4
  provider: ^4.0.5
  stream_chat_flutter: ^0.2.0-alpha+2
  virtual_keyboard: ^0.1.4
  # Firebase
  cloud_firestore: ^0.13.0+1
  firebase_auth: ^0.16.0
  firebase_messaging: ^6.0.9
  firebase_storage: ^3.1.1
  # UI
  awesome_dialog: ^0.1.1
  badges: ^1.1.0
  bot_toast: ^2.2.1
  bubble: ^1.1.9+1
  cached_network_image: ^2.0.0
  cupertino_icons: ^0.1.3
  flutter_inner_drawer: ^0.5.4
  flutter_staggered_grid_view: ^0.3.0
  font_awesome_flutter: ^8.5.0
  photo_view: ^0.9.1
  popup_menu: ^1.0.5
  pull_to_refresh: ^1.5.8
  shimmer: ^1.0.1
  styled_widget: ^0.0.6
  # State Managment
  flutter_mobx: ^1.1.0
  flutter_modular: ^1.1.2
  freezed_annotation: ^0.7.1
  # hive_flutter: ^0.3.0+1
  # hive: ^1.4.1+1
  mobx: ^1.2.0
  # Utils
  analyzer: ^0.39.8
  built_collection: ^4.3.2
  built_value: ^7.1.0
  email_validator: ^1.0.4
  google_fonts: ^0.3.9
  image_picker: ^0.6.3+1
  intl: ^0.16.1
  logger: ^0.8.3
  path_provider: ^1.5.1
  permission_handler: ^5.0.0
  timeago: ^2.0.25
  url_launcher: ^5.4.1
  uuid: ^2.0.4
  video_player: ">=0.10.10 <2.0.0"
  mock_cloud_firestore: ^0.0.20
  firebase_auth_mocks:
    git: git@github.com:atn832/firebase_auth_mocks.git

dev_dependencies:
  flutter_driver:
    sdk: flutter

  build_runner: ^1.9.0
  built_value_generator: ^7.1.0
  built_value_test: ^7.1.0
  mobx_codegen: ^1.1.0
  mockito: ^4.1.1
  pedantic: ^1.9.0
  test: ^1.14.3
  test_coverage: ^0.4.1

flutter:
  uses-material-design: true
  assets:
    - assets/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
