name: highvibe
description: HighVibe Network
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.8

environment:
  sdk: ">=2.8.4 <3.0.0"
  flutter: 1.19.0-4.3.pre # The latest checked version by @minikin on Flutter Beta channel

dependencies:
  agora_rtc_engine: ^1.0.12
  audioplayers: ^0.15.1
  badges: ^1.1.0
  bip39: ^1.0.3
  built_collection: ^4.3.2
  built_value: ^7.1.0
  cached_network_image: ^2.2.0+1
  camera: ^0.5.7+4
  chopper: ^3.0.3
  cloud_firestore: ^0.13.7
  cupertino_icons: ^0.1.3
  dartz: ^0.9.1
  dio: ^3.0.9
  dotted_border: ^1.0.6
  easy_permission_validator: ^2.0.0
  ed25519_hd_key: ^1.0.1
  email_validator: ^1.0.4
  file_picker_web: ^1.0.1+2
  file_picker: ^1.13.0+1
  firebase_auth: ^0.16.1
  firebase_messaging: ^6.0.16
  firebase_ml_vision: 0.9.3+5
  firebase_storage: ^3.1.6
  flappy_search_bar: ^1.7.2
  flare_flutter: ^2.0.3
  flushbar: ^1.9.1
  flutter_apns: ^1.1.0
  flutter_facebook_login: ^3.0.0
  flutter_inner_drawer: ^0.5.4
  flutter_launcher_icons: ^0.7.5
  flutter_local_notifications: ^1.4.1
  flutter_mobx: ^1.1.0
  flutter_modular: ^1.3.1
  flutter_phoenix: "^0.1.0"
  flutter_signin_button: ^1.0.0
  flutter_spinkit: ^4.1.2+1
  flutter_staggered_grid_view: ^0.3.0
  flutter_svg: ^0.18.0
  font_awesome_flutter: ^8.5.0
  google_fonts: ^0.3.9
  google_sign_in: ^4.5.1
  intl: ^0.16.1
  lottie: ^0.4.0+1
  mobx: ^1.2.1+1
  path_provider: ^1.6.11
  path: ^1.6.4
  permission_handler: ^5.0.0
  photo_view: ^0.9.1
  popup_menu: ^1.0.5
  progress_dialog: ^1.2.4
  provider: ^3.1.0+1
  pull_to_refresh: ^1.5.8
  qr_flutter: ^3.1.0
  shared_preferences: ^0.5.6+1
  shimmer: ^1.1.1
  styled_widget: ^0.0.6
  timeago: ^2.0.25
  universal_html: ^1.2.3
  url_launcher: ^5.4.1
  uuid: ^2.2.0
  video_player: ">=0.10.11+2 <2.0.0"
  virtual_keyboard: ^0.1.4
  web_socket_channel: ^1.1.0
  web3dart: ^1.2.3

dev_dependencies:
  flutter_driver:
    sdk: flutter

  build_runner: ^1.10.0
  built_value_generator: ^7.1.0
  built_value_test: ^7.1.0
  firebase_storage_mocks: ^0.1.0
  mobx_codegen: ^1.0.3
  mock_cloud_firestore: ^0.0.20
  mockito: ^4.1.1
  pedantic: ^1.9.0
  test_coverage: ^0.4.1
  test: ^1.14.3
  firebase_auth_mocks:
    git: git://github.com/atn832/firebase_auth_mocks.git

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/animation/
    - assets/emoji/
    - assets/icons/
    - assets/web/
    - assets/images/
