name: highvibe
description: HighVibe Network
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.9

environment:
  sdk: ">=2.8.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  agora_rtc_engine: ^1.0.12
  animations: ^1.0.0+5
  audioplayers: ^0.15.1
  awesome_dialog: ^0.1.1
  badges: ^1.1.0
  bot_toast: ^2.2.1
  bubble: ^1.1.9+1
  built_collection: ^4.3.2
  built_value: ^7.1.0
  cached_network_image: ^2.0.0
  camera: ^0.5.7+4
  cloud_firestore: ^0.13.0+1
  cupertino_icons: ^0.1.3
  dartz: ^0.9.1
  dio: ^3.0.9
  easy_permission_validator: ^2.0.0
  email_validator: ^1.0.4
  file_picker: ^1.12.0
  firebase_auth: ^0.16.0
  firebase_messaging: ^6.0.9
  firebase_auth_mocks:
    git: git://github.com/atn832/firebase_auth_mocks.git
  firebase_storage_mocks: ^0.1.0
  firebase_storage: ^3.1.1
  flappy_search_bar: ^1.7.2
  flutter_apns: ^1.1.0
  flutter_inner_drawer: ^0.5.4
  flutter_launcher_icons: ^0.7.5
  flutter_local_notifications: ^1.4.1
  flutter_mobx: ^1.1.0
  flutter_modular: ^1.2.3
  flutter_spinkit: ^4.1.2+1
  flutter_staggered_grid_view: ^0.3.0
  flutter_svg: ^0.17.4
  font_awesome_flutter: ^8.5.0
  freezed_annotation: ^0.7.1
  google_fonts: ^0.3.9
  google_sign_in: ^4.4.6
  image_picker: ^0.6.3+1
  intl: ^0.16.1
  logger: ^0.8.3
  lottie: ^0.4.0+1
  mobx: ^1.2.0
  mock_cloud_firestore: ^0.0.20
  path: ^1.6.4
  path_provider: ^1.5.1
  permission_handler: ^5.0.0
  photo_view: ^0.9.1
  popup_menu: ^1.0.5
  # provider: ^4.0.5
  pull_to_refresh: ^1.5.8
  progress_dialog: ^1.2.4
  shimmer: ^1.1.1
  stream_chat_flutter: ^0.2.0-alpha+2
  styled_widget: ^0.0.6
  timeago: ^2.0.25
  url_launcher: ^5.4.1
  uuid: ^2.1.0
  video_player: ">=0.10.11+1 <2.0.0"
  virtual_keyboard: ^0.1.4
  gradient_text: ^1.0.2
  flutter_facebook_login: ^3.0.0
  flare_flutter: ^2.0.3

  # ethereum wallet
  web3dart: ^1.2.3
  provider: ^3.1.0+1
  # mobx: ^1.0.1
  # flutter_mobx: ^1.0.1
  bip39: ^1.0.3
  ed25519_hd_key: ^1.0.1
  shared_preferences: ^0.5.6+1
  web_socket_channel: ^1.1.0
  # intl: ^0.16.0
  # flutter_spinkit: ^4.1.1+1
  qr_flutter: ^3.1.0
  # camera: ^0.5.7+4
  firebase_ml_vision: 0.9.3+5
  firebase_analytics: ^5.0.11
  # url_launcher: ^5.4.1
  flutter_phoenix: "^0.1.0"
  chopper:
  flushbar: ^1.9.1
  # firebase_auth: ^0.16.0
  # google_sign_in: ^4.4.4
  flutter_signin_button: ^1.0.0
  # flutter_facebook_login: ^3.0.0
  decimal: ^0.3.0


dev_dependencies:
  flutter_driver:
    sdk: flutter

  build_runner: ^1.10.0
  built_value_generator: ^7.1.0
  built_value_test: ^7.1.0
  dependency_validator: ^1.0.0
  mobx_codegen: ^1.0.3
  mockito: ^4.1.1
  pedantic: ^1.9.0
  test_coverage: ^0.4.1
  test: ^1.14.3

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/animation/
    - assets/icons/
    - assets/emoji/
    - assets/images/