name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v1
        with:
          channel: "beta"
          flutter-version: 1.19.0-4.3.pre 
          # The latest checked version by @minikin on Flutter Beta channel.
          # We need to use the specific version because Flutter has some regressions on the beta channel.

      - name: Install dependencies
        run: flutter pub get

      - name: Flutter clean
        run: flutter clean

      - name: Install dependencies
        run: flutter pub get

      - name: Run builder
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Analyzing project
        run: flutter analyze

      - name: Run tests
        run: flutter test
