name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: 
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - uses: subosito/flutter-action@v1
      with:
       channel: 'stable'
   
    - name: Flutter clean
      run: flutter clean
      
    - name: Install dependencies
      run: flutter pub get
      
    - name: Run builder
      run: flutter pub run build_runner build --delete-conflicting-outputs
      
    - name: Analyzing project
      run: flutter analyze
      
    - name: Run tests
      run: flutter test
